-- phpMyAdmin SQL Dump
-- version 4.1.14
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Sep 03, 2014 at 09:17 PM
-- Server version: 5.5.37-log
-- PHP Version: 5.3.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `joomlavi_karaoke`
--

-- --------------------------------------------------------

--
-- Table structure for table `casi`
--

DROP TABLE IF EXISTS `casi`;
CREATE TABLE IF NOT EXISTS `casi` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tencs` varchar(255) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=55 ;

--
-- Dumping data for table `casi`
--

INSERT INTO `casi` (`id`, `tencs`) VALUES
(29, 'The Men'),
(30, 'Y Moan'),
(31, ' Đàm Vĩnh Hưng'),
(32, 'Kasim Hoàng Vũ'),
(33, 'Nguyễn Phi Hùng'),
(34, 'Bằng Cường - Khánh Phương'),
(35, 'Cao Thái Sơn'),
(36, 'Duy Mạnh'),
(37, 'Đàm Vĩnh Hưng'),
(38, 'Phạm Khánh Hưng'),
(39, 'Lâm Hùng'),
(40, 'Vân Quang Long'),
(41, 'Nhật Tinh Anh'),
(42, 'Nhóm GMC'),
(43, 'Trần Tâm'),
(44, 'Ưng Hoàng Phúc'),
(45, 'Điền Thái Toàn'),
(46, 'Trọng Tấn'),
(47, 'akira phan'),
(48, 'Châu Gia Kiệt'),
(49, 'Lâm Chấn Huy'),
(50, 'Trịnh Tuấn Vỹ'),
(51, 'Bằng Kiều'),
(52, 'Châu Việt Cường'),
(53, 'Đan Trường'),
(54, 'Lam Trường');

-- --------------------------------------------------------

--
-- Table structure for table `list`
--

DROP TABLE IF EXISTS `list`;
CREATE TABLE IF NOT EXISTS `list` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `tenbh` varchar(255) NOT NULL,
  `mabh` int(11) DEFAULT NULL,
  `casi` varchar(255) DEFAULT NULL,
  `nhacsi` varchar(255) DEFAULT NULL,
  `member` varchar(255) DEFAULT NULL,
  `loibh` text,
  `idCaSi` int(11) DEFAULT '0',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=69 ;

--
-- Dumping data for table `list`
--

INSERT INTO `list` (`id`, `tenbh`, `mabh`, `casi`, `nhacsi`, `member`, `loibh`, `idCaSi`) VALUES
(20, 'Gọi Tên Em Trong Đêm', 0, 'The Men', 'Nhạc Hoa lời Việt', '', 'Đêm nghe hạt mưa rơi lòng chợt nhớ em vô cùng\r\nChuyện Tình ngày ấy k sao quên đc\r\nGiờ 2 ta ở 2 nơi lòng người có nghĩ đến bao giờ\r\nLúc trước anh ra đi là có lý do\r\nNếu biết trước tương lai anh đã chẳng yêu em\r\nNhưng con tim anh đây thật k sao quên đc em người ơi\r\nNước mắt đã rơi vì nhớ em mong em trong từng đêm vắng\r\nMong cho em luôn được hạnh phúc nơi phương trời xa\r\nGọi tên em trong đêm trái tim này xót xa\r\nNgười yêu ơi hãy quên những năm tháng êm đềm hôm nào\r\nGọi tên em trong đêm để mình anh chịu nỗi đắng cay\r\nMột thế giới khác mang anh đi chẳng thể nào có em\r\nGọi tên trong đêm\r\nsẽ chẳng thể có nhau\r\ntình duyên ta thế thôi chắc có lẽ đã đc ăn bài\r\ngọi tên em trong đêm để mình anh chịu nỗi đớn đau\r\nmột thế giới khác mang anh đi chia đôi tình chúng ta cách xa 2 phương trời\r\nmong em qua bao đêm\r\ntrái tim này xót xa\r\nngười ơi yêu ơi hãy quên tình nồng say từng năm tháng\r\nGọi tên trong đêm\r\nđể mình anh chịu nỗi đắng cay\r\nmột thế giới khác mang anh đi chẳng thể nào có em\r\nGọi tên trong đêm\r\nsẽ chẳng thể có nhau\r\ntình duyên ta thế thôi chắc có lẽ đã đc ăn bài\r\ngọi tên em trong đêm để mình anh chịu nỗi đớn đau\r\nmột thế giới khác mang anh đi chia đôi tình chúng ta cách xa 2 phương trời. ', 29),
(21, 'Giấc Mơ Cha Pi', 34532, 'Y Moan', 'Trần Tiến', '', 'Ở nơi ấy, tôi đã thấy trên ngọn núi cao có hai người, chỉ có hai người yêu nhau. . . .\r\nHọ đã sống không mùa đông, không mùa nắng, mưa. có một mùa, chỉ có một mùa yêu nhau. . . .\r\nỞ nơi ấy, đàn dê trắng nhởn nhơ trên đồi, một mái tranh nghèo, một nhà sàn đơn sơ.\r\nỞ nơi ấy, họ đã sống cuộc sống yên bình. Ai nghèo cũng có cây đàn ChaPi.\r\nKhi rung lên, từng sợi dây đàn đã đong đầy hồn người Đak-lay.\r\n\r\nƠi Đak-lay, ơi rừng cây ngọn núi vang tiếng đàn ChaPi\r\nAi yêu tự do, yêu rừng xanh thì lên núi nghe đàn ChaPi\r\nTôi yêu ChaPi không còn cô đơn, không buồn, không vui.\r\nKhi nghe ChaPi chợt thấy nao lòng một giấc mơ\r\nÔi ChaPi. ', 30),
(22, 'Tiếng Gió Xôn Xao', 0, ' Đàm Vĩnh Hưng', '', '', 'Gió vẫn hát thì thầm đến bên tôi như thật gần\r\nGió muốn nói điều gì tha thiết\r\nGió vẫn nhắc một người đã ra đi không trở lại\r\nLỡ mất chuyện tình không thể quên\r\nBước những chuỗi ngày dài ấp ôm bao đêm huyền diệu\r\nÁnh mắt ấy giờ này xa lắm\r\nThoáng phút chốc giật mình ngỡ như em đang thật gần\r\nGió đánh thức vì tôi ngủ mê\r\nThắp ánh sáng bước qua đêm thâu\r\nChờ mong ngày mai khát vọng\r\nVà gió vẫn thế gió mang tôi đi tìm em\r\nDẫu có lúc nước mắt tuôn rơi\r\nNhư hạt sương, hạt sương bé nhỏ\r\n\r\nGió sẽ hát rì rào\r\nGió ru tim tôi ngày ngày mãi xôn xao ', 31),
(23, 'Tôi Là Ai Em Là Ai', 0, 'Kasim Hoàng Vũ', '', '', 'Đêm qua tôi nằm mơ thấy em,\r\nTrong giấc mơ em là của ai\r\nĐêm qua em nằm mơ thấy tôi,\r\nNhưng giấc mơ không phải là tôi\r\n\r\nTôi yêu em, từng đêm nhớ em\r\nTôi lang thang để được gần em\r\nTôi không tin rằng trong giấc mơ,\r\nEm bên ai không phải là tôi\r\n\r\nEm dịu dàng như tia sáng trong đêm,\r\nĐem yêu thương phủ lên trên cuộc đời\r\nTôi ngập ngừng bước đến bên em,\r\nÔi bỗng nhiên sao em lại tan biến\r\n\r\nMưa thì thầm như anh nói yêu em\r\nEm đưa tay đón cơn mưa vào lòng\r\nNhưng đừng là giấc mơ đêm qua\r\nTôi cho em nụ hôn ban đầu\r\n\r\nTôi là ai mà cứ mãi yêu em\r\nEm là ai mà cứ mãi yêu tôi ', 32),
(24, 'Vì Yêu ', 52114, 'Kasim Hoàng Vũ', '', '', 'Nắm tay nhau trên đường tung tăng vui ca ngày tháng\r\nDấu chân xưa ghi lại đôi ta yêu nhau ngày ấy\r\nTóc em xanh vì anh, mắt anh vui vì em\r\nChung bước vì yêu.\r\n\r\nBiết em yêu anh nhiều đôi khi anh hay lạc lối\r\nGió đưa anh quay về cùng em trong đêm mịt tối\r\nMắt môi xưa còn đây\r\nChiếc hôn nay vụt bay\r\nBay xa tầm tay.\r\n\r\nYêu dù là xa ở nơi đâu anh xin được yêu\r\nXa dù thật xa nếu đôi ta yêu nhau thật sâu\r\nMuôn nghìn trùng không chia cách\r\nđôi mình cùng yêu nhau mãi\r\nVới em vì tình yêu anh sẽ...\r\n\r\nChờ em xa vòng tay và thứ tha cho anh ngày ấy\r\nNơi đây mình anh tìm bóng em như chim lạc lối\r\nNgày chờ, đêm khóc mưa trong lòng giông tố\r\nDứt mưa sao chưa dứt nỗi buồn? ', 32),
(25, 'Đứa Bé', 0, '', 'Minh Khang', '', 'Trong đêm một bàn chân bước\r\nBé xíu lang thang trên đường\r\nÁnh mắt buồn, mệt nhoài của em\r\nEm rất buồn vì em không biết đi, đi về đâu\r\n\r\nCuộc sống mưu sinh chỉ làm em qua cơn đói từng ngày\r\nVì em không cha, vì em đã mất mẹ\r\nThương đau vẫn là đau thương\r\n\r\nEm mơ một vì sao sáng\r\nDẫn lối em trên đường đời\r\nDẫu biết rằng chỉ là giấc mơ\r\nĐã lâu rồi em đã không, không có tình thương\r\n\r\nNhìn thấy ai ai cũng đều vui bên mẹ cha\r\nGiọt lệ em tuôn rơi, hòa tan với nỗi buồn\r\nBước đi trong chiều mưa\r\n\r\nHãy lau khô cuộc đời em\r\nBằng tình thương, lòng nhân ái của con người\r\nVà hãy lau khô giọt nước mắt trong lòng em\r\nBằng tất cả trái tim con người Việt Nam... ', NULL),
(26, 'Nỗi lòng xa xứ', 0, 'Nguyễn Phi Hùng', '', '', 'Một mình nơi đây nhớ thương chốn quê nhà\r\nCuộc đời công nhân bao bồn bề âu lo\r\nTa tìm gì đây giữa xa hoa thị thành\r\nLùa vội chén cơm cho kịp giờ tan ca\r\nPhòng trọ đơn sơ bữa cơm với dưa cà\r\nBạn bè quanh ta bao mọi miền quê xa\r\nLưu lạc về đây sống tha phương từng ngà\r\nVận đời nỗi trôi theo dòng đời mưu sinh\r\nThương mẹ cha đang mong chờ con từng giờ\r\nThương đàn em thơ ngây vang tiếng cười đùa\r\nMưa lũ tràn về trắng xóa cánh đồng xanh\r\nMái nhà yên ấm bông hoa mỏng manh\r\nMong một mai cơn giống tố sẽ dần qua\r\nChút tiền lương bao năm con gửi về nhà\r\nMong gia đình mình được sống an vui\r\nNỗi lòng xa xứ chẳng thẻ nào nguôi.', 33),
(27, 'Tôn thờ một tình yêu', 0, 'Bằng Cường - Khánh Phương', 'Bằng Cường', '', 'Từng năm tháng vô tình vì người yêu dối gian mình\r\nCó lúc con tim ta như lặng thinh\r\nNgười cất bước ra đi, từng đêm ta khóc chia ly\r\nBiết đến bao lâu ta thôi mộng mơ.\r\n\r\nLòng ta mãi tôn thờ tình yêu này đến bao giờ\r\nDẫu biết em nay không quay về đây.\r\n(Dẫu biết nay em sẽ không về đây.)\r\nNhiều khi muốn hỏi lòng: tại sao ta mãi hy vọng\r\nƯớc muốn bên em ta như ngày xưa.\r\n\r\nTình tan vỡ thôi từ đây ân tình cũng như làn mây\r\nCứ trôi hoài cứ phiêu du như tình em xa mãi.\r\nTình tan vỡ thôi người ơi, nhớ làm gì và chờ gì nữa\r\nThế nhưng sao lòng vẫn không thể quên được người.\r\n\r\nNgười yêu hỡi bao lệ rơi lúc đêm về lặng thầm cay đắng\r\nChỉ riêng anh bước đơn côi thà nước mắt rơi từng đêm.\r\n(Chỉ riêng anh bước đơn côi trong từng đêm hoang vắng.)\r\nNgười yêu hỡi sao lòng anh mãi không quên dù tình đã hết\r\nCứ trông mong, cứ yêu thương về em. ', 34),
(31, 'Cầu Vồng Sau Mưa', 0, 'Cao Thái Sơn', 'Nguyễn Văn Chung', '', 'Đứng giữa con đường mưa anh vô tình nhớ một nụ cười\r\nĐứng giữa con đường mưa anh vô tình nhớ một vòng tay\r\nNhững kỷ niệm ngày xưa thôi mong chờ cũng thôi hy vọng\r\nĐã có khi tưởng như trái tim này cũng thôi mộng mơ.\r\nNhưng rồi anh tìm thấy những kỷ niệm từ khi gặp em\r\nNhưng rồi anh tìm thấy những nụ cười cho anh niềm vui.\r\nTạm biệt nhé những nỗi đau ơi\r\nTạm biệt nhé nỗi nhớ một thời\r\nVì có em, anh chỉ cần 1 vòng tay ấm ôm lấy anh.\r\nĐể ngày mai anh biết yêu hơn\r\nNiềm hạnh phúc mới đến dịu êm\r\nCám ơn em vì đã cho anh một tình yêu..! ', 35),
(32, 'Kiếp Đỏ Đen', 0, 'Duy Mạnh', 'Duy Mạnh', '', 'Giờ ta chẳng còn chi, mãi trắng tay mà thôi.\r\nĐầu bạc, răng long, phũ phàng.\r\nTiền có kiếm như nước rồi cũng sẽ trôi hết.\r\nTay không trắng tay lại về không.\r\nĐời phiêu lưu là thế không biết đâu ngày mai, nên giờ đây mới đắng cay.\r\nNgồi trước tấm gương sáng rọi vào đó mới thấy thân xác hoang tàn không nhận ra.\r\nTa mang bao tội lỗi nên thân ta giờ đây, kiếp sống không nhà, không người thân.\r\nTa mang bao tôi lỗi, người ơi ta đâu còn chi xin hãy tránh xa kiếp đỏ đen ', 36),
(33, 'Một thời đã xa', 0, 'Đàm Vĩnh Hưng', '', '', 'Đừng buồn anh hỡi khi lỡ nói yêu em rồi\r\nBận lòng chi nữa hỡi anh xin hãy quên em đi\r\nGiây phút bên nhau anh sẽ quên mau\r\nChỉ có em thôi giữ mãi bóng hình xưa\r\nĐời ai cũng có giây phút trót yêu dại khờ\r\nVà em đã biết biết anh sẽ chẳng yêu em đâu\r\nEm sẽ không quên giây phút bên nhau\r\nEm đã trao anh trao anh nụ hôn ấy\r\n\r\nVà em biết anh sẽ quên hết\r\nNhững bài tình ca viết riêng tặng em\r\nVà em biết trái tim anh có hình bóng ai kia đâu chỉ riêng em\r\nVà em sẽ không trách anh nữa\r\nChẳng trách anh đâu\r\nKhi ta đến bên nhau tình gian dối .\r\n\r\nVà em biết anh sẽ quên hết những bài tình ca viết riêng tặng em\r\nVà em biết trái tim anh có hình bóng ai kia đâu chỉ riêng em\r\nVà em sẽ không trách anh nữa\r\nChẳng trách anh đâu\r\nKhi ta đến bên nhau\r\nTình yêu dối lừa . ', 37),
(34, 'Giây phút chia xa', 345311, 'Duy Mạnh', '', '', 'Giờ chia tay nhau đã đến\r\nCòi tàu thét vang trong màn đêm\r\nHãy hôn nhau đi lần cuối\r\nGiòng lệ tuôn rơi mặn đắng\r\nNgẹn ngào xiết đôi bàn tay\r\nLòng ta nghe sao lạnh giá\r\n\r\nĐoàn tàu lăn bánh rời bến\r\nChầm chậm khuất xa dần xa\r\nĐã đưa em đi người hỡi\r\nĐể lại con tim đau nhói\r\nLõi loi bước đi giữa màn đêm\r\nGiòng lệ vẫn mãi tuôn trào\r\n\r\nThời gian trôi qua thật mau\r\nGiờ tàu biết đi về đâu ?\r\nNụ hôn yêu thương còn ấm môi\r\nMà em đã ra đi về nơi phương xa người hỡi\r\n\r\nDù cho xa nhau mãi mãi\r\nTình anh vẫn trao về em\r\nTừ trong con tim vẫn mong chờ\r\nRồi mai đây em sẽ quay trở về .. ', 36),
(35, 'Hết Rồi', 0, 'Đàm Vĩnh Hưng', '', '', 'Một ngày em đi đến nơi xa vời xóa hết bao buồn thương.\r\nmột thời bên nhau ái ân nồng xay, giờ tìm hoài không thấy .\r\nNgười yêu ơi em nỡ quên sao đành,\r\nTình tôi bơ vơ trái tim giá lạnh\r\nNhớ em một mình đi mãi.\r\n\r\nNhìn thời gian trôi tháng năm mong chờ dưới bóng đêm lẻ loi.\r\nNgồi đây tôi mơ giấc mơ bình yên được trọn đời bên em.\r\nTrời xanh bao la hỡi em nơi nào,\r\nMình tôi lang thang gió mưa thét gào\r\nBiết là giấc mơ xa vời.\r\n\r\nBao đam mê ngày xưa cũng đi qua rồi,\r\nTrong con tim đầy vơi bóng em mà thôi.\r\nGiờ còn chi nữa đâu vì em thay đổi\r\nMột cuộc tình ấm êm ai ngờ gian rối.\r\nEm cho tôi buồn đau biết bao đêm rồ,\r\nNay em quay về đây muốn ta thành đôi.\r\nVề đi thôi hỡi em đừng nên tiếc nuối\r\nChuyện tình mình đã bay theo làn sương khói', 37),
(36, ' Lợi Danh', 4324, 'Phạm Khánh Hưng', 'Phạm Khánh Hưng', '', 'Dòng đời trôi qua thật nhanh\r\nCuộc sống đua trên câu Lợi Danh\r\nLòng cứ ngỡ khi ta giàu sang sẽ không ưu phiền\r\nTừng ngày qua tâm hồn ta chôn vùi trong ý nghĩa bạc vàng\r\nNên không tin vào ai, thật lòng với ai.\r\n\r\nRồi nay khi ta đã có được những chi trong ta hằng mong\r\nCàng lìa xa đi bao tình thân đã yêu thương ta\r\nChẳng cần ai, không cần ai! Tiền sẽ mua cho ta niềm vui\r\nNên đời ta chỉ biết sống cho riêng mình.\r\n\r\nĐK:\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nĐể giờ đây ta đang nhìn ta như người xa lạ\r\nCuộc sống ganh đua đổi thay chính ta\r\nNhạt mờ đi theo bao ngày qua lương tâm của ta.\r\n\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nNhìn lại ta quanh ta giờ đây hiu quạnh riêng mình\r\nTiền có cho ta trọn vẹn chữ vui ?\r\nHay chỉ làm ta thêm chẳng tin những ai gần ta.\r\n\r\nThời gian vẫn cứ đi mãi\r\nĐời nỗi trôi theo bao được thua\r\nĐể hôm nay khi câu Lợi Danh đã không vững bền\r\nGiàu mà chi ? Sang mà chi ? Rồi có ai đau thương vì ta ?\r\nNay mình ta chua xót, khóc cho thân mình ! ', 38),
(37, 'Lợi Danh', 0, 'Phạm Khánh Hưng', 'Phạm Khánh Hưng', '', 'Dòng đời trôi qua thật nhanh\r\nCuộc sống đua trên câu Lợi Danh\r\nLòng cứ ngỡ khi ta giàu sang sẽ không ưu phiền\r\nTừng ngày qua tâm hồn ta chôn vùi trong ý nghĩa bạc vàng\r\nNên không tin vào ai, thật lòng với ai.\r\n\r\nRồi nay khi ta đã có được những chi trong ta hằng mong\r\nCàng lìa xa đi bao tình thân đã yêu thương ta\r\nChẳng cần ai, không cần ai! Tiền sẽ mua cho ta niềm vui\r\nNên đời ta chỉ biết sống cho riêng mình.\r\n\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nĐể giờ đây ta đang nhìn ta như người xa lạ\r\nCuộc sống ganh đua đổi thay chính ta\r\nNhạt mờ đi theo bao ngày qua lương tâm của ta.\r\n\r\nMột kiếp phong ba xô đời ta, cuốn thân ta đi thật xa\r\nNhìn lại ta quanh ta giờ đây hiu quạnh riêng mình\r\nTiền có cho ta trọn vẹn chữ vui ?\r\nHay chỉ làm ta thêm chẳng tin những ai gần ta.\r\n\r\nThời gian vẫn cứ đi mãi\r\nĐời nỗi trôi theo bao được thua\r\nĐể hôm nay khi câu Lợi Danh đã không vững bền\r\nGiàu mà chi ? Sang mà chi ? Rồi có ai đau thương vì ta ?\r\nNay mình ta chua xót, khóc cho thân mình ! ', 38),
(40, 'Được và mất', 0, 'Lâm Hùng', '', '', 'Hoi nhan the con tin ai nua ko .\r\nkhi niem tin gan xa noi cuoi troi\r\nnguoi doi thay trang den ko doan dc\r\nbao loi noi chi trot luoi dau moi\r\nko la chi tinh than luon vay quanh\r\nchut loi danh dan chia 2 con nguoi\r\nduoc va mat may ai tu hieu minh\r\ntien la giay cach chia doi nghia tinh\r\n\r\nCao sang thap hen duyen so nao biet ai vuong mang\r\nhon nhau la nghia nhan trong moi nguoi\r\ndoi dau chi la the , cuoi doi dau chi la the\r\nai ko tro ve mo dat sau\r\n\r\nThe thai nhan tinh doi thay bang nhung cau chua cay\r\nhon thua la chu nhan de luu doi\r\ndoi khi co duoc mat , so troi cho ta ma thoi\r\nko ai gianh lay duoc dau ', 39),
(41, 'Trà Xanh', 0, 'Vân Quang Long', '', '', 'Ngày hôm qua ngỡ như là, một giấc mơ - giấc mơ buồn\r\nNgày hôm qua, nắng hay mưa, anh với em vẫn tìm nhau.\r\nChờ đợi nhau lúc ban mai; đón đưa nhau mỗi khi tan trường\r\nCùng buồn vui, cùng ước mơ một ngày mai.\r\nNgày hôm qua với chiếc xe đạp, anh đón em rong chơi kháp nơi\r\nCùng sẻ chia, chiếc hôn đầu\r\nCùng sẻ chia, ngụm trà xanh…\r\nVà anh mơ, mơ đến một ngày: đón đưa em với xe thật đẹp.\r\nEm ngồi bên, lộng lẫy như một nàng tiên!\r\n\r\nThế mà em xa anh đành lòng!\r\nĐể mộng ước tan vỡ như vậy sao?\r\nChiếc xe đạp ngày hôm qua, năm lặng lẽ chợt nghe xót xa\r\nMỗi lần anh đi qua nới này…Ngụm Trà Xanh…\r\nĐắng trong lòng.\r\nNỗi nhớ mong làm đôi chân thẩn thờ.\r\nNgày hôm qua đã xa rồi…\r\nEm đã quên quên anh thật rồi\r\nNgày hôm qua đã xa rồi..\r\nEm đã quên ly Trà Xanh\r\nNgày hôm qua vẫn như còn\r\nBoa ước mơ anh chon trong lòng\r\nNgày hôm qua vẫn như còn\r\nAnh vẫn nhớ ly Trà Xanh', 40),
(42, 'Vầng Trăng Khóc', 0, 'Nhật Tinh Anh', 'Nguyễn Văn Chung', '', 'Đã ko còn người yêu hỡi\r\nNgày xưa ấy đôi ta bên nhau ko rời\r\nNgồi trên cát, nhìn biển đêm\r\nHát vu vơ mấy câu tình ca\r\n\r\nTrái tim buồn vì thương nhớ\r\nVì đau xót sao đôi ta mau chia lìa\r\nĐời giông bão nhiều đắng cay\r\nCuốn trôi mau biết đâu tình nồng\r\n\r\nThì thôi em, đừng mong nhớ, đừng thương tiếc chi thêm đau lòng\r\nTình chúng ta, đã phôi pha, em và anh mỗi người 1 nơi\r\nNgồi nơi đây, mình đơn côi vầng trăng khóc sao rơi sông dài\r\nTiếc cho tôi, tiếc cho người\r\nVà cho bao yêu thương đã trao\r\nGió đông buồn\r\n\r\nKhóc chi người, vì anh bik nào ai muốn mai sau chia li đôi đường\r\nTình yêu đến, chợt bỏ đi, mấy ai vui với nhau muôn đời\r\nChắc khi nào tìm duyên mới, thì anh sẽ mau quên đi bao ân tình\r\nVà em chúc người mới quen sẽ bên anh yêu anh thật lòng\r\n\r\nThì thôi em, đừng mong nhớ, đừng thương tiếc chi thêm đau lòng\r\nTình chúng ta, đã phôi pha, em và anh mỗi người 1 nơi\r\nNgày mai sau dù gặp nhau thì xin hãy cho nhau 1 lời\r\nĐể ko quên những êm đềm mà tình yêu khi xưa đã trao\r\nGiấc mơ đầu ', 41),
(43, 'Đêm Lang Thang', 0, 'Đàm Vĩnh Hưng', 'Vinh Sử', '', 'Bước lang thang qua từng vỉa hè\r\nBiết đi đâu đêm dài bơ vơ\r\nNgười yêu ơi! Em đã sang ngang\r\nTình yêu ơi! Xin vấn khăn tang\r\nAnh mất em đời như cánh diều băng sang\r\n\r\nSống lang thang nhưkẻkhông nhà\r\nMới xa em nghe buồn nghĩa trang\r\nNgười yêu ơi! Em chắc đang vui\r\nNào em hay anh rất đơn côi\r\nGom góp kỷ niệm giây phút tình chia phôi\r\n\r\n" Em ơi em ơi\r\nThà rằng ngày xưa em đừng thề\r\nTrong cuộc đời yêu mãi anh thôi\r\nThì ngày nay anh đâu muộn phiền\r\nKhi em ngoảnh mặt cho anh bỏ cuộc trong nước đua tình\r\n\r\nEm ơi em ơi\r\nThà rằng ngày xưa em đừng thề\r\nTrong cuộc đời yêu chỉ anh thôi\r\nThì ngày nay anh đâu tuyệt vọng\r\nPhong ba ngập lòng trông theo bụi hồng em bước vu quy "\r\n\r\nCứ lang thang như kẻ điên cuồng\r\nBiết đi đâu đêm dài bơ vơ\r\nTừ Duy Tân khu phố công viên\r\nVề Gia Long bay lá me nghiêng\r\nKhông bước chân nàng, anh buốt lạnh con tim\r\n\r\nNhắc lại Đk : "..."\r\n\r\nMuốn quên em, quên đời, quên người\r\nMới lang thang như kẻ tha phương\r\nTrời cho anh con số không may\r\nĐể yêu em mang lấy chua cay\r\nAnh chiếc ga nhỏ cho chuyến tàu em qua\r\n\r\nBước lang thang như kẻ điên cuồng\r\nBiết đêm nay đi về nơi đâu\r\nVẫn lang thang như kẻ không nhà\r\nBiết đi đâu đêm dài bơ vơ\r\nMuốn quên em mới lang thang\r\nBiết đêm nay về nơi đâu ? ', 37),
(44, 'Nước Mắt Kẻ Đa Tình', 0, 'Duy Mạnh', 'Duy Mạnh', '', 'Tôi như ngừơi điên lang thang giữa đêm trường\r\nBước thấp bước cao đi ngả nghiêng\r\nĐêm nay còn tôi say sưa với nỗi buồn\r\nUống đi cho quên tình cay đắng\r\n\r\nTôi mơ về em cho tôi những tháng năm\r\nQuấn quít lấy nhau những nụ cười\r\nBây giờ chia tay nhau ôm nỗi đau trong lòng\r\nCố uống cho say nhưng nào quên\r\n\r\nHỡi người tình lúc xưa tôi mang tội\r\nKiếp sống của một kẻ đa tình\r\nYêu một người vẫn mơ hai, ba người\r\nGây cho em nhiều đau đớn\r\n\r\nHãy nhìn lại thế gian ai như mình\r\nHối tiếc bây giò đã muộn\r\nEm đi bây giờ, tôi đang oán trách mình\r\nTại sao tôi lại nỡ đi yêu nhiều người ', 36),
(45, 'Tình mãi theo ta', 0, 'Nhóm GMC', 'Lê Quang', NULL, 'Bóng chim cuối trời<br/>\r\n\r\nVút bay chốn nào<br/>\r\n\r\nHát lên hỡi người<br/>\r\n\r\nTình yêu còn mãi nơi đây,<br/>\r\n\r\nHát lên nhớ thương<br/>\r\n\r\nĐã xa lắm rồi<br/>\r\n\r\nBước chân xuống đường<br/>\r\n\r\nCòn nghe tình mãi theo ta.<br/>\r\n\r\n1.\r\n\r\nLòng còn mang thương nhớ xin em quay về đây<br/>\r\n\r\nĐời phù du em hỡi xin iu nhau ngày sau<br/>\r\n\r\nBài tình ca anh viết trên đôi môi tình nhân<br/>\r\n\r\nLời dịu êm anh hát đưa em qua giấc mơ.<br/>\r\n\r\nHát cho tình còn đến nơi đây anh chờ<br/>\r\n\r\nLá thu rơi ngoài ngõ ngỡ bước chân em<br/>\r\n\r\nBiết em đang ngồi khóc bên hiên mưa về<br/>\r\n\r\nNắng rơi trên đường vắng cô đơn,<br/>\r\n\r\nĐừng buồn em... hỡi.<br/>\r\n\r\n2.<br/>\r\n\r\n(rap...)<br/>\r\n<br/>\r\n3.\r\n\r\nNgười iu dấu ơi về đây với anh<br/>\r\n\r\nNgười iu dấu ơi, xin cho bình yên. <br/>', 42),
(46, 'Kiếp Lữ Hành', 0, 'Nhóm GMC', 'Minh Châu', NULL, 'Khi màn đêm buông xuống<br/>\r\nTừng bước chân rơi trên lòng đường<br/>\r\nTrôi về nơi quên lãng<br/>\r\nChôn dấu đi vết đau ngày tháng<br/>\r\nChơi vơi cánh chim bay<br/>\r\nThời gian in hằn bao đổi thay<br/>\r\nĐôi chân đi về đâu<br/>\r\nGiữa không gian bao trùm nỗi sầu<br/>\r\nBao lần ta mơ ước<br/>\r\nDừng bước chân lãng du mỏi mòn<br/>\r\nKhi tình yêu lên tiếng<br/>\r\nSau tháng năm bấy lâu tìm kiếm<br/>\r\nĐã nắm giữ trong tay<br/>\r\nĐể rồi tan tành như khói mấy<br/>\r\nRưng rưng đôi bàn tay<br/>\r\nVẫn trông mong tin yêu về đây<br/>\r\nChờ mong những phút giây<br/>\r\nĐón yêu thương quanh ta vơi đầy<br/>\r\nDừng chân dưới bóng cây<br/>\r\nGiữa thiên đường ta đã thấy<br/>\r\nĐể hạnh phúc mãi trong tầm tay<br/>\r\nNhững ưu tư đã vụt bay<br/>\r\nBàn chân hoang nay đã về<br/>\r\nBước qua bóng đêm mộng mê <br/>', 42),
(47, 'Kiếp Tình Chung', 0, 'Trần Tâm', 'Lê Minh Kha', NULL, 'Có những lúc khi yêu nhau anh đâu hay duyên tình ta chua cay Cố xóa hết bao yêu thương mong quên khi đường tình chia đôi Anh quay đi lòng đắng cay Lệ tuôn rơi trong đêm phân vân biết nói sao Em giờ đang trong vòng tay một người anh quen Có nước mắt nơi con tim khi đôi ta không còn yêu như xưa Sẽ khó nói em đâu hay em đang yêu chung một người như anh Nay tim anh giờ nhói đau Đành quay gót chúc phúc suốt kiếp cho người yêu Mong em được vui và quên dĩ vãng kiếp tình chung Nào ai biết trong tình yêu Lòng đau xót nhìn người bước đi Trách chi ai hẹn thề Giờ đây bội ước ân tình xưa Thầm mong ước em đẹp đôi Tình yêu ấy đành nhưòng lối đi Trái tim anh thật lòng chúc cho em hạnh phúc ', 43),
(48, 'Tâm Sự Hai Người Đàn Ông', 0, 'Ưng Hoàng Phúc', 'Vũ Quốc Việt', NULL, 'Tôi kể anh nghe tình tôi ngày ấy đang yên vui<br/>\r\nBỗng một ngày cô ta đành lòng lặng bỏ tôi ra đi<br/>\r\nNgày đêm chỉ biết lo cho em tình xây đắp mong em vui<br/>\r\nTình trao hết để được gì giờ thì trắng tay<br/><br/>\r\n\r\nTôi cũng chẳng hơn anh đâu<br/>\r\nNhiều khi đời tôi như thèm uống cho say hết<br/>\r\nMong quên đi bao đau thương em gieo trong trái tim này<br/>\r\nĐời tôi nào biết khi xa hoa nào chẳng dám yêu thêm ai<br/>\r\nMong được sống cùng tình yêu với em thôi<br/><br/>\r\n\r\nThế anh lầm quá<br/>\r\nChính anh cũng thế mà<br/>\r\nÔi nào ngờ đâu bao năm qua chẳng thua ai<br/>\r\nNhưng hôm nay ngậm ngùi thôi ta đành bó tay<br/>\r\nChớ nên gục ngã<br/>\r\nHãy thương đời ta (chính ta)<br/>\r\nĐời tôi và anh sao hao hao giống như nhau<br/>\r\nÔi hai người đàn ông<br/>\r\nCó ai đoán được chữ ngờ<br/>\r\n\r\nChúng ta là hai người đàn ông giống nhau <br/><br/><br/>', 44),
(49, 'Cánh hoa tàn', 0, 'Điền Thái Toàn', 'Thái Khang', NULL, 'Người ta đã bỏ tôi đi thât rồi người ơi, người ta đã không còn yêu như ngày xưa. Khi con người ta đã muốn thay lòng, dẫu có tiếc thương xót đau níu kéo cũng vậy thôi. Yêu em nên tôi ngậm cay đắng mối tình căm, chỉ mong sao cho em được hạnh phúc. Cầu mong cho ai kia bên người yêu thật lòng, còn tôi sẽ ra đi không phiền tình người nữa đâu. Thời gian ngỡ như tim tôi không còn bao muộn phiền, ngờ đâu trái ngang làm tim tôi vỡ tan. Khi bên người ta em quá dại khờ, trót trao tấm thân trắng trong con gái chỉ vì đâu. Bên em bao nhiêu lời khuyên nhũ cho đời em, chớ nên yêu đam vì mù quáng. Rồi em đã ra đi không một lời từ biệt, chiều nay chốn nhân gian ngậm ngùi hẹn người kiếp sau.<br/><br/>\r\nĐời em còn đó những ánh sáng hy vọng cớ sao đành thế, vội chi em không tin để vùi chôn chốn đọa đầy. Người tôi yêu ra đi bỏ lại nhân gian tình thương vì sao thế ai ơi vì sao thế. Nằm nơi lạnh giá em nghe không cõi lòng nát tan vụn vỡ, mẹ cha em buông lơi thét từng cơn đau kêu gào, vòng hoa theo em đi dòng người đưa em đi về đâu đằng sau những tiếng nấc khóc thương đời em, tựa như canh hoa tàn\r\nNgười đăng: Thanhhoapro - Đặng Thanh Hòa( Tin1b) ', 45),
(50, 'Việt Nam trên đường chúng ta đi', 0, 'Trọng Tấn', 'Huy Du', NULL, 'Việt Nam trên đường chúng ta đi<br/>\r\nNghe gió thổi đồng xanh quê ta đó<br/>\r\nNghe sóng biển ầm vang xa tận tới chân trời<br/>\r\nNghe ấm lòng những khi đang dồn bước<br/>\r\nMà vui sao ta chẳng nói nên lời.<br/><br/>\r\n\r\nDặm đường xa, ta đi giữa mùa xuân<br/>\r\nTa đi giữa tình thương của Đảng<br/>\r\nTiếng Bác Hồ rung động mãi trong tim<br/>.\r\nĐường ta đi soi ánh lửa đêm dài<br/>\r\nĐường ta về trong nắng ấm ban mai.<br/>\r\nViệt Nam ! Việt Nam !<br/>\r\nQua từng bước gian nan<br/>\r\nLớn lên rồi đẹp những mùa xuân...<br/><br/>\r\n\r\n\r\nTa đi qua phố qua làng<br/>\r\nNgọn đèn sáng giục lòng ta đó<br/>\r\nLời mẹ nói ấm lòng đẹp sao<br/>\r\nĐàn em vui ríu rít mái trường.<br/>\r\n\r\nTa đi đường rợp bóng hàng dương<br/>\r\nĐất bom đào đã lên màu cỏ mới<br/>\r\nNhững cặp mắt đêm đêm trông đợi<br/>\r\nChiến trường xa dồn dập những chiến công.<br/><br/>\r\n\r\n* Miền Nam ơi ! Miền Nam!<br/>\r\nHỡi những dòng sông soi bóng dừa xanh<br/>\r\nNhững đỉnh núi khuất mây mờ xa tắp<br/>\r\nTa sẻ đến nơi đâu còn giặc<br/>\r\nTa chưa về khi tổ quốc chưa yên...<br/>\r\nViệt Nam ! Việt Nam ! Ôi tổ quốc vinh quang... <br/>', 46),
(51, 'Cắn Rứt', 0, 'Ưng Hoàng Phúc', 'Quang Huy', NULL, 'Đã nhiều lần muốn nói chia tay cùng em từ lâu.<br/>\r\nNhưng ngại vì chẳng biết nói sao để em chẳng buồn.<br/>\r\nVì sai lầm em chẳng có,<br/>\r\nđau buồn tôi chẳng có...<br/>\r\nTại sao? Tôi muốn chia tay....<br/><br/>.\r\n\r\nChắc tại vì tôi đã hết yêu từ lâu mà thôi,<br/>\r\nSuốt đời này tôi chẳng muốn em bị tôi dối lừa<br/>\r\nThì thay vì tôi giấu kín,<br/>\r\nthôi thì tôi nói hết...<br/>\r\nRằng tôi đã hết yêu em, bước đi thì hơn.<br/><br/>\r\n\r\nMà lòng tôi cũng chẳng muốn em thôi<br/>\r\nVì tôi đã khóc bao đêm,<br/>\r\nBuồn làm chi em ơi,<br/>\r\ntình yêu đã hết lâu nay<br/>\r\nThay vì ta cố gắng, cũng chẳng được gì nữa đâu<br/>\r\nTại sao, không giữ những ấn tượng đẹp với nhau.<br/>\r\nRồi mai đây em sẽ tìm đc ai đó yêu em hơn tôi<br/>\r\nĐừng cố chấp đi tìm cảm giác đôi ta khi xưa, qua rồi..<br/>\r\nTôi mong một người nào đó,<br/>\r\ncho em được hạnh phúc hơn...<br/>\r\nVì tôi đã chẳng làm được cho em khi xưa....<br/>\r\nLúc em bên tôi..... <br/>', 44),
(52, 'Ngôi sao kia có phải là mai', 0, 'akira phan', '', NULL, 'Đoạn 1:<br/>\r\nNgàn vì sao đêm nay,chiếu sáng nhân gian an lành,vầng trăng khuyết chứng minh tình yêu ta.<br/>\r\n\r\nNgồi bên em,đưa tay ôm lấy bờ vai pé xinh,làn hơi ấm ta trao nhau trong màn đêm.<br/>\r\n\r\nGiọt sương khuya rơi rơi em thấy lạnh ko hỡi người mà lòng anh tái tê tình như tơ<br/>\r\n\r\nVì anh bik bên em thêm chỉ vài giây phút thôi,nhưng vẫn mỉm cười để em yêu tôi được vui<br/>\r\n\r\nĐK: Giọt nước mắt đau thương cũng đã rơi,bàn tay anh khẽ buông lời vì tôi biết em yêu tôi sắp xa tôi rồi<br/>\r\n\r\nLại thêm một vì sao sáng soi hỏi vì sao kia có nghe ko,ở trên cao ngôi sao kia có phải là em…..<br/>\r\n\r\nĐoạn 2<br/>\r\n\r\nNgàn vì sao đêm nay,chiếu sáng nhân gian an lành,vầng trăng khuyết chứng minh tình yêu ta.<br/>\r\n\r\nNgồi bên em,đưa tay ôm lấy bờ vai pé xinh,làn hơi ấm ta trao nhau trong màn đêm.<br/>\r\n\r\nGiọt sương khuya rơi rơi em thấy lạnh ko hỡi người mà lòng anh tái tê tình như tơ.<br/>\r\n\r\nVì anh bik bên em thêm chỉ vài giây phút thôi,nhưng vẫn mỉm cười để em yêu tôi được vui<br/>\r\n\r\nĐK: Giọt nước mắt tôi cũng đã rơi,bàn tay anh khẽ buông lời vì tôi biết em yêu tôi sắp xa tôi rồi<br/>\r\n\r\nLại thêm một vì sao sáng soi,hỏi vì sao kia có nghe ko,ở trên cao ngôi sao kia có phải là em<br/>\r\nGiọt sương khuya rơi rơi em thấy lạnh ko hỡi người mà lòng anh tái tê tình như tơ<br/>\r\nVì anh bik bên em thêm chỉ vài giây phút thôi,nhưng vẫn mỉm cười để em yêu tôi được vui.<br/>\r\nGiọt nước mắt tôi cũng đã rơi,bàn tay anh khẽ buông lời vì tôi biết em yêu tôi sắp xa tôi rồi<br/>\r\nLại thêm một vì sao sáng soi,hỏi vì sao kia có nghe ko,ở trên cao ngôi sao kia có phải là em…..<br/>\r\nỞ trên cao ngôi sao kia….có phải…có phải là em. <br/><br/>', 47),
(53, 'Kiếp Đam Mê', 0, 'Châu Gia Kiệt', '', NULL, 'Tôi xin người cứ gian dối<br/>\r\nCho tôi tưởng người cũng yêu tôi<br/>\r\nCho tôi còn được thấy đời vui<br/>\r\nKhi cơn mưa mùa đông đang đến<br/>\r\nXin giã từ ngày tháng rong chơi<br/><br/>\r\n\r\nĐôi tay này vẫn chờ mong<br/>\r\nCon tim này dù lắm long đong<br/>\r\nTôi yêu người bằng nỗi nghiệt oan<br/>\r\nKhông than van và không trách oán<br/>\r\nCho tôi trọn một kiếp đam mê<br/><br/>\r\n\r\nÔi tôi ước mơ anh bỏ cuộc vui<br/>\r\nTrở về căn phòng này đơn côi<br/>\r\nMôi anh ru nỗi đau tuyệt vời<br/>\r\nKhi màn đêm phủ lứa đôi<br/>\r\nLà thời gian cũng như ngừng trôi<br/>\r\nThương yêu này người hãy nhận lấy<br/>\r\nôm tôi đi môi hôn tràn đầy<br/>\r\nTrong tay người hồn sẽ mù say<br/>\r\nbao khốn khó vụt bay<br/><br/>\r\n\r\nTôi không cần và nghi ngại khi<br/>\r\nAi chê bai thân tôi khờ dại<br/>\r\nTôi yêu người hồn chẳng tình trong<br/>\r\nTôi vẫn cứ đợi mong<br/><br/>\r\n\r\nTôi xin người cứ gian dối<br/>\r\nCho tôi tưởng người cũng yêu tôi<br/>\r\nCho tôi còn được thấy đời vui<br/>\r\nKhi cơn mưa mùa đông đang đến<br/>\r\nTôi xin người cứ gian dối<br/>\r\nNhưng xin người đừng lìa xa tôi <br/><br/><br/>', 48),
(54, 'Xin Lỗi Anh Sẽ Ra Đi', 0, 'Châu Gia Kiệt', 'Quách Beem', NULL, 'Em yêu hỡi hãy về bên anh một lân thôi<br/>\r\nEm yêu đừng giân anh nữa hãy tin lòng anh<br/>\r\nBởi trong tim anh chỉ yêu em hỡi người<br/>\r\nEm yêu hỡi hãy nghe anh nói một lần nữa thôi<br/>\r\nEm yêu hỡi đừng lặng thinh mãi để tim nhói đau<br/>\r\nĐừng quay đi để nước mắt rơi chàn mi./<br/><br/>\r\nĐk:\r\nVà rồi ngày mai bóng tối khuất lấp phía chân trời<br/>\r\nThiếu anh trên đời biết sẽ còn ai chăm lo cho em<br/>\r\nĐoạn đường em đi ngày mai sẽ vắng bóng anh đi cùng<br/>\r\nKhó khăn ai nắm tay em vượt qua<br/>\r\nLỗi lầm ngày xưa anh xin giữ mãi trong tim mình<br/>\r\nChỉ mong một ngày em sẽ hiểu ra thứ tha cho anh<br/>\r\nXin chúc em luôn bình yên êm ấm trên môi nụ cười<br/>\r\nXin lỗi người anh sẽ ra đi vì em. <br/>', 48),
(55, 'Kiếp Lang Thang', 0, 'Lâm Chấn Huy', '', NULL, 'Còn lại gì khi giờ tay trắng tay<br/>\r\nĐi lang thang đã bao tháng ngày<br/>\r\nTay chân run xác thân mỏi mệt<br/>\r\nQuanh đời ta giờ chẳng còn ai.<br/><br/>\r\n\r\nVì cuộc đời không như ai ước mơ<br/>\r\nBiết ngày mai sẽ đi về đâu?<br/>\r\nKhi quanh ta đã không còn gì<br/>\r\nTiền chẳng có, mà tình cũng không.<br/><br/>\r\n\r\nTa giờ đây ta phải làm điều gì<br/>\r\nCứ lang thang như kẻ không nhà<br/>\r\nĐi về đâu khi cuộc chơi đã tàn<br/>\r\nBuổi tiệc tan thân xác hoang tàn.<br/><br/>\r\n\r\nDòng đời trôi mãi như nước cuốn trôi đời ta<br/>\r\nVì làn khói trắng ru đời để mãi lãng quên<br/>\r\nVà khi thân xác hoang tàn thì chẳng còn ai với ta<br/>\r\nGiờ ta chỉ muốn quay về lại vết thương ngày xưa.<br/>\r\n\r\nNgày xưa ta đã lỗi lầm tìm về chốn ăn chơi<br/>\r\nMẹ cha đã khóc thật nhiều khóc thương cho thằng con.<br/>\r\nĐời ai cũng có lỗi lầm một lần để mãi không quên<br/>\r\nGiờ ta chỉ muốn trở về nhà để quên đi kiếp lang thang.<br/><br/><br/>', 49),
(56, 'Đâu Chỉ Có Mình Em', 0, 'Trịnh Tuấn Vỹ', '', NULL, 'Nếu như là trò đùa, thì anh đây sẽ đau chi một lần thôi, vẫn yêu người một đời cớ sao em nỡ dối lòng anh, nhìn dòng đời xô đây cuốn em đi xa khuất chân trời, còn mình ta đứng nhìn cuộc tình lẽ loi, nếu như chẳng còn gì thì ngày xưa chớ nên gieo cho tình yêu, để yêu người dồi đành, nói chia tay tan nát đời ta thà một lần để biết có dối gian để thấy long người, bởi vì em muốn quên thì anh chẳng còn là chi, thà là chia tay anh đau trong niềm hạnh phúc, còn hơn anh thấy em đi bên ai mà nhớ hai, có nỗi đau nào bằng tình yêu của anh trao em như kẻ chộm tình hãy tập cho tim ta không cô đơn khi hình bóng người xa ,ngoài trời mưa dơi nghe con tim mình nhức nhói vì tình yêu thế gian đôi tim yêu đành thế sao ,anh vẫn tin một ngày rồi anh sẽ quên đi bao đau thương trong đời, rồi ngày mai đây anh tin nhân gian đâu chỉ có mình em hỡi người yêu ơi.... thà là chia tay anh đau trong niêm hạnh phúc, còn hơn anh thấy em đi bên ai mà nhớ hai ,có nỗi đau nào bằng tình yêu của anh trao em như kẻ chộm tình, hãy tập cho tim ta không cô đơn khi hình bóng người xa ngoài trời mưa dơi nghe con tim mình nhức nhói vì tình yêu thế gian đôi tim yêu đành thế sao, anh vẫn tin một ngày rồi anh sẽ quên đi bao đau thương trong đời, rồi ngày mai đây anh tin nhân gian đâu chỉ có mình em, hỡi người yêu ơi.', 50),
(58, 'Say Tình', 0, 'Đàm Vĩnh Hưng', '', NULL, 'Rót mãi những chén chua cay này<br/>\r\nLêu bêu như gã du ca buồn<br/>\r\nLang thang bước với nỗi đau<br/>\r\nVới trái tim ta tật nguyền.<br/><br/>\r\n\r\nBuồn nào đưa ta qua những nỗi đau thương này<br/>\r\nDặn lòng ta say cho quên đi đôi mắt nỗi u tình<br/>\r\nÁnh mắt đắm đuối, đôi môi đam mê, đôi tay buông lơi<br/>\r\nEm yêu đã giết ta trong một đêm gây mê buồn.<br/>\r\n\r\nVì yêu em nên ta đã hóa ngây ngô rồi<br/>\r\nMỗi sáng, mỗi tối, ta điên, ta say với bóng men<br/>\r\nĐã thế những nỗi đau thương nỗi chua cay đâu không ai hay,<br/>\r\nKhi em đã bước theo tình vui kia đi rồi.<br/><br/>\r\n\r\nNào ngờ em quay lưng cho ta quá đau buồn<br/>\r\nGiữa quãng đời làm người tình si quá mê dại<br/>\r\nÔm lòng vỡ nát,<br/>\r\nTrút hết trong ly rượu nồng.<br/><br/>\r\n\r\nĐã trót, đã lỡ yêu em rồi<br/>\r\nCon tim ta lỡ trao em rồi<br/>\r\nTa say, ta hát nghêu ngao lời tình si mê,<br/>\r\nEm có hay không nào. <br/><br/><br/><br/>', 37),
(59, 'Khóc Cho Người Ra Đi', 0, 'Châu Gia Kiệt', '', NULL, 'o lai day chi con hai chung ta<br/>\r\nnoi ra di nhung suy tu buon phien<br/>\r\nngai ngun chi vi ngay mai cach xa<br/>\r\nse khong con gi de oan trach nhau<br/>\r\nnguoi tinh oi du long em doi thay<br/>\r\ntrai tim toi van mong em duoc vui<br/>\r\ndung ban tamve chuyen hai chung ta<br/>\r\ncuoc tinh minh xem nhu la con gio<br/>\r\nnguoi tinh oi ta da khong song duoc voi nhau<br/>\r\nthi danh chia tay nhung giac mo ma thoi<br/>\r\nnhung ngay vui ta ben nhau oi dep lam sao<br/>\r\nlong quan dau nhin ve nhung ngay xua<br/>\r\ntinh xua nghia cu se khong bao gio lang quen<br/>\r\ndu ngay mai da mai mai khong con nhau<br/>\r\nthoi danh chon sau trong tim mot cuoc tinh dau<br/>\r\ngiot nuoc mat khoc cho nguoi di <br/>', 48),
(60, 'Con Đường Mưa', 0, 'Cao Thái Sơn', 'Nguyễn Văn Chung', NULL, 'Nếu ngày xưa bước đi nhanh qua con đường mưa.<br /> \r\nThì anh đã không gặp người.<br/>\r\nNếu ngày xưa em nhìn anh nhưng không mỉm cười.<br/>\r\nThì anh đã không mộng mơ.<br/>\r\nNếu tình ta chẳng phải xa khi đang đậm sâu.<br/>\r\nThì anh đã không đau buồn.<br/>\r\nNếu lòng anh không còn yêu em hơn chính mình.<br/>\r\nThì anh đã quên được em .<br/>.<br/>\r\nĐK: Làm sao để đường xưa đừng in dấu chân anh mỗi ngày Làm sao cho lòng anh thôi gọi tên em trong mỗi giấc mơ.<br/>\r\nLàm sao để mưa mùa thu đừng rơi khi anh đang nhớ em..<br/>\r\nLàm sao khi thấy mưa anh không buồn .<br/>\r\nLàm sao để quên niềm vui niềm hạnh phúc khi anh có người Làm sao quên ngày chia tay lệ em rơi trên đôi mắt cay.<br/>\r\nLàm sao để thôi chờ mong Làm sao tim anh thôi đừng mơ rằng ngày mai thấy em quay trở về *** .<br/>\r\nNếu ngày xưa bước đi nhanh qua con đường mưa Thì anh đã không gặp người.<br/>\r\nNếu ngày xưa em nhìn anh nhưng không mỉm cười Thì anh đã không mộng mơ.<br/>\r\nNếu thời gian có quay về trước khi gặp em .<br/>\r\nThì anh vẫn xin đi cùng Nếu ngày xưa mưa mùa thu rơi trên lối về Thì anh vẫn không vội qua <br/><br/>', 35),
(61, 'Đêm Trăng Tình Yêu', 0, 'Nhóm GMC', '', NULL, 'Chiều một mình trên phố năm xưa<br/>\r\nLạc bước giữa đêm đông người<br/>\r\nRồi một ngày em bỗng đi qua<br/>\r\nSưởi ấm trái tim anh lẻ loi<br/><br/>\r\n\r\nNụ cười ngọt ngào ánh mắt đam mê<br/>\r\nTrái tim đôi ta không rời<br/>\r\nCon thuyền không xa bến<br/>\r\nCon thuyền không còn theo sóng mãi xa mù khơị<br/>\r\n\r\nLòng ngập ngừng nói tiếng yêu em<br/>\r\nLời yêu ấy thiết tha chân thành<br/>\r\nCòn gì bằng sánh bước bên nhau<br/>\r\nCùng ngắm ánh trăng và ngàn sao<br/><br/>\r\n\r\nCuộc tình ngọt ngào em đã trao anh<br/>\r\nLàm trái tim anh đổi thay<br/>\r\nNiềm hạnh phúc anh đang có em<br/>\r\nKhiến anh ngỡ ngàng.<br/><br/>\r\n\r\nĐK:<br/><br/>\r\n\r\nPhố xa đêm đông người đêm tình yêu dưới trăng<br/>\r\nThấp thoáng bao đôi nhân tình đang đùa vui đắm say<br/>\r\nCành hồng trao tay đến tay<br/>\r\nRộn ràng nghe tim ngất ngây<br/>\r\nTình này trao em thề mãi không bao giờ phai<br/><br/>\r\n\r\nƯớc chi trăng đừng tàn soi tình yêu chúng ta<br/>\r\nNhững ánh sao băng qua trời xin lặng im lung linh<br/>\r\nThì thầm anh nói với em một lời<br/>\r\nEm có biết được trái tim anh yêu mình em. <br/><br/><br/>', 42),
(62, 'Vùng Trời Bình Yên', 0, 'Đàm Vĩnh Hưng', 'Đàm Vĩnh Hưng', NULL, 'Mây lang thang buồn trôi<br/>\r\nNặng mang ưu tư khát khao trong tim tháng ngày<br/>\r\nTheo mưa rơi lạnh câm<br/>\r\nTừng đêm em nghe xót xa anh ơi có hay<br/>\r\nGiữa bóng tối chập chùng<br/>\r\nTình anh như giấc mơ xanh bao hi vọng<br/>\r\nDẫn lối bước em về dìu em qua đắng cay<br/>\r\nXua mây đen tan nhanh<br/>\r\nMặt trời bừng tia nắng tươi lung linh ấm nồng<br/>\r\nKhi cơn mưa vụt qua<br/>\r\nTình yêu đưa ta thoát cơn phong ba bão giông<br/>\r\nKhuất lấp những đêm dài<br/>\r\nMặt trời luôn chiếu soi cho em yêu đời<br/>\r\nXóa hết những nghi ngờ tình yêu như khúc ca<br/>\r\nTừng vòng tay trao hơi ấm rộn rã<br/>\r\nĐôi tim mừng vui gặp gỡ<br/>\r\nTrong ngày mới nắng say tình dâng ngập lối<br/>\r\nNắng len qua hàng cây gió mơn man đùa lả lơi đàn bướm<br/>\r\nBước chân vui hạnh phúc, nắm tay ta về vùng trời bình yên<br/><br/>', 37),
(63, 'Khúc Biệt Ly', 0, 'Bằng Kiều', '', NULL, 'Đã như mây âm thầm đợi chờ.<br/>\r\nRồi bay theo bao cơn gió đi về đâu?<br/>\r\nCung đàn anh giờ đây vắng em.<br/>\r\nVà tiếng hát theo mây mưa về nơi xa..<br/>\r\nHãy mang theo ân tình ngày nào..<br/>\r\nCùng ra đi cho anh nói câu biệt ly.<br/>\r\nÔm tình ta buồn trong giá băng.<br/>\r\nChờ ai nữa em ơi!Cung đàn nhạt phai..<br/><br/>\r\n\r\nBao đam mê có em trong ngày tháng.<br/>\r\nAnh làm sao để vơi hết nỗi buồn.<br/>\r\nÔi chia ly biết em vui tình mới.<br/>\r\nSao lòng anh giờ đây vắng tanh..<br/>\r\nĐã phai mờ, những ân tình cố quên rồi<br/>\r\ncũng qua..lỡ xa rồi cánh chim trời hãy giữ mãi<br/>\r\ntiếng ca ngày xưa..<br/>\r\nĐã phai mờ, những ân tình cố quên rồi cũng qua.<br/>\r\nLỡ xa rồi cánh chim trời, hây giữ mãi tiếng ca<br/>\r\nngày xưa.. <br/><br/>', 51),
(64, 'Bạc trắng tình đời', 0, 'Châu Việt Cường', '', NULL, 'Ngày mai tôi sẽ cố quên người<br/>\r\nCho dù em có quay về đây<br/>\r\nNgày mai tôi sẽ rời xa em<br/>\r\nCho dù em còn yêu tôi<br/>\r\nBạc trắng như vôi tình đời<br/>\r\nMàu đen cho cuộc tình hồng<br/>\r\nTình nghĩa đôi ta từ đây<br/>\r\nNhư vầng trăng gặp CƠN giông bão<br/>\r\nThà là bỏ đi hết ta làm lại từ đầu<br/>\r\nThà là bỏ đi hết ta chẳng nợ gì nhau<br/><br/>\r\n\r\nCho quên đi đớn đau<br/>\r\nKhỏi bận tâm ngày sau<br/>\r\nVì một người như thế có đáng hay không<br/>\r\nChuyện thường tình như thế Sao tA lại buồn phiền<br/>\r\nVÌ MỘT NGƯỜI NHƯ THẾ Sao nước mắt cứ tuôn rơi<br/>\r\nChắc là tại vì tôi không yêu NHƯ người ta<br/>\r\nMau yêu mau quên như bong bóng bay <br/><br/><br/>\r\n\r\n', 52),
(65, 'Dòng sông băng', 0, 'Đan Trường', '', NULL, 'Nếu có nước mắt nếu có yêu thương<br/>\r\nMênh mông dòng sông thì thầm cùng em<br/>\r\nTiếng hát ấy vút cao hoà vào trời xanh<br/>\r\nNhững lúc buốt giá níu kéo con tim<br/>\r\nKhông gian lặng im một dòng sông băng<br/>\r\nMong ban mai đưa ánh dương về cùng dòng sông...<br/><br/>\r\n\r\nCó nỗi nhớ khắc ghi tuổi thơ<br/>\r\nNơi phương xa một mùa đông băng giá<br/>\r\nCó tuyết trắng che lấp con đường<br/>\r\nĐôi chân em con dốc dài lạnh căm<br/>\r\nCó tiếng hát lướt trên dòng sông<br/>\r\nNhư con tim em buồn vui muốn nói<br/>\r\nCó cô gái ôm giấc mơ hồng<br/>\r\nGiữa trời đông lạnh lùng.<br/><br/>\r\n\r\nNhìn dòng sông thân thương ôm tuổi thơ<br/>\r\nHàng thông che dáng ai giữa đôi bờ<br/>\r\nTrời vào đông mênh mang những nỗi nhớ<br/>\r\nCho em khung trời ước mơ. <br/><br/>', 53),
(66, 'Thư Gửi Em', 0, '', '', NULL, 'Chắc em đâu hay ngày qua có những thứ anh kìm nén ở trong đáy lòng<br/>\r\nĐâu ngờ những gì xảy ra cho anh chỉ vừa mới hôm qua<br/>\r\nĐã dõi theo em khoảng thời gian anh bên em không thể tin tất cả những gì<br/>\r\nEm đã đi đâu khi trời đêm xuống anh không thấy em<br/><br/>\r\nĐK:<br/><br/>\r\nAnh đã thấy em đi với ai rồi<br/>\r\nAnh đã thấy từng người mà em đã đi khi về đêm<br/>\r\nAnh đã thấy phấn son rồi,giày cao gót nước hoa thơm ngát<br/>\r\nAnh đã nghĩ sẽ phải thứ tha người<br/>\r\nAnh đã nghĩ rằng mình sẽ xóa hết nỗi đau về em<br/>\r\nNhưng mà không chỉ một người<br/>\r\nNgày mai anh sẽ cố quên tất cả vì em<br/>\r\nCuối thư anh trao những ngày đã viết cho em những ngày tới<br/>\r\nHãy luôn mỉm cười quên hết đi đi tìm cho em bầu trời vun đầy những yêu thương<br/>\r\nNếu có ai bên em suốt đời cho em bao nhiêu là nhan sắc,tuổi xuân má hồng<br/>\r\nAnh vẫn hi vọng bên người em yêu sẽ hạnh phúc hơn <br/><br/>', 0),
(67, 'Hãy Xem Là Giấc Mơ', 0, '', '', NULL, 'Ngok A à em yêu anh nhiều lắm, Quỳnh s2 Anh :x có buồn đau cũng phải chịu thôi hỡi em.<br/>\r\nVài hôm nữa thì em đã đi theo người.<br/>\r\nCó ai muốn sớt chia tình đâu hỡi em.<br/>\r\nVì đôi ta chỉ có duyên không nợ nhau.<br/>\r\nChuyện gì đến cuối cùng cũng đã đến.<br/>\r\nThì thôi anh xin chúc em bên người.<br/>\r\nSẽ hạnh phúc ấm êm đừng lo tới anh.<br/>\r\nMà mất đi tương lai tốt dẹp người ơi.<br/>\r\nRồi từ đây đôi ta hai lối,đường của em em cứ bước đi.<br/>\r\nVà hãy xem như hai chúng ta chưa từng gặp.<br/>\r\nNgày mai lỡ nếu có gặp nhau,một hai câu quan tâm đến nhau.<br/>\r\nRồi đi thôi đừng để trái tim ngậm ngùi.<br/>\r\nVà hãy quên anh đi người ơi,hãy xem như là một giấc mơ.<br/>\r\nVì đôi ta đã đến với nhau quá bất ngờ.<br/>\r\nThời gian cho đôi ta đã hết,người hãy đi đi lưu luyến chi.<br/>\r\nHãy xem như ngày xưa chúng ta sống tạm mà thôi.<br/><br/>\r\n\r\nRồi từ đây đôi ta hai lối,đường của em em cứ bước đi.<br/>\r\nVà hãy xem như hai chúng ta chưa từng gặp.<br/>\r\nNgày mai lỡ nếu có gặp nhau,một hai câu quan tâm đến nhau.<br/>\r\nRồi đi thôi đừng để trái tim ngậm ngùi.<br/>\r\nVà hãy quên anh đi người ơi,hãy xem như là một giấc mơ.<br/>\r\nVì đôi ta đã đến với nhau quá bất ngờ.<br/>\r\nThời gian cho đôi ta đã hết,người hãy đi đi lưu luyến chi.<br/>\r\nHãy xem như ngày xưa chúng ta sống tạm mà thôi.<br/>\r\nThì hãy xem như là một giấc mơ,qua rồi <br/><br/>', 0),
(68, 'Tôi Ngàn Năm Đợi', 0, 'Lam Trường', '', NULL, 'cơn gió lạnh thật buồn , khiến tình tôi lang mang , ánh trăng tàn ủa vàng , tôi nhìn em miên man', 54);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
